# Ref: https://docs.gitlab.com/ee/ci/yaml
image:
  name: bufbuild/buf:1.17.0
  entrypoint: [""]

# TODO: include slack notification to notify of running jobs
# include:
#   - project: sanctumlabs/tools/gitlab-ci
#     file: templates/slack-notification.yml

variables:
  BUF_CACHE_DIR: ".cache"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  PIPELINE_NAME: 'Message Defs pipeline'

workflow:
  name: 'Pipeline for branch: $CI_COMMIT_BRANCH'

cache:
  key: "$CI_COMMIT_REF_SLUG"
  untracked: false
  paths:
    - ".cache"

stages:
  - lint
  - build
  - publish
  - package

lint:
  stage: lint
  script:
    - buf format -d --exit-code
    - buf lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH"
    - if: "$CI_COMMIT_TAG"

breaking:
  stage: build
  needs:
    - lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - buf breaking --against "${CI_REPOSITORY_URL}#branch=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}"

generate:
  stage: build
  needs:
    - lint
  script:
    - buf generate
  artifacts:
    paths:
      - "lib"
    when: always
    expire_in: 1 week
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH"
    - if: "$CI_COMMIT_TAG"

# release the next tag automatically and only on the main branch when manually triggered
release:
  stage: publish
  needs:
    - generate
  image: node:18
  variables:
    GITLAB_TOKEN: ${CI_JOB_TOKEN}
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install -g semantic-release @semantic-release/gitlab
  script:
    - semantic-release
  only:
    - main
  when: manual

push-buf-registry:
  stage: publish
  script:
    # Generate the libraries, these will be passed on to the next jobs in the pipeline
    - buf generate
    - echo ${BUF_API_TOKEN} | buf registry login --username ${BUF_USER} --token-stdin
    - buf push shared -t "${CI_COMMIT_TAG}"
    - buf push eventing -t "${CI_COMMIT_TAG}"
    - buf push transport -t "${CI_COMMIT_TAG}"
  only:
    - tags

publish-python:
  stage: package
  image: python:3.8
  needs:
    - push-buf-registry
  script:
    - cd lib/python
    - make publish-gitlab
  only:
    - tags

publish-javascript:
  stage: package
  image: node:20.4.0
  needs:
    - push-buf-registry
  script:
    - cd lib/js
    - echo @sanctumlabs:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/>.npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - make publish-gitlab
  only:
    - tags

publish-maven:
  stage: package
  image: gradle:7.4-jdk8
  needs:
    - push-buf-registry
  script:
    - cd lib/kotlin
    - ./gradlew -Pversion="${CI_COMMIT_TAG}" publish
  only:
    - tags
