image:
  name: bufbuild/buf:1.17.0
  entrypoint: [""]

variables:
  BUF_CACHE_DIR: ".cache"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  untracked: false
  paths:
    - ".cache"

stages:
  - lint
  - build
  - publish

lint:
  stage: lint
  script:
    - buf format -d --exit-code
    - buf lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH"
    - if: "$CI_COMMIT_TAG"

breaking:
  stage: build
  needs:
    - lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - buf breaking --against "${CI_REPOSITORY_URL}#branch=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}"

generate:
  stage: build
  needs:
    - lint
  script:
    - buf generate
  artifacts:
    paths:
      - "lib"
    when: always
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH"
    - if: "$CI_COMMIT_TAG"

push-buf-registry:
  stage: publish
  needs:
    - generate
  script:
    - echo ${BUF_API_TOKEN} | buf registry login --username ${BUF_USER} --token-stdin
    - buf push shared -t "${CI_COMMIT_TAG}"
    - buf push eventing -t "${CI_COMMIT_TAG}"
    - buf push transport -t "${CI_COMMIT_TAG}"
  only:
    - tags

publish-python:
  stage: publish
  image: python:3.8
  needs:
    - push-buf-registry
  dependencies:
    - generate
  script:
    - cd lib/python
    - make publish-gitlab
  only:
    - tags

publish-javascript:
  stage: publish
  image: node:20.4.0
  needs:
    - push-buf-registry
  dependencies:
    - generate
  script:
    - cd lib/js
    - echo @sanctumlabs:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/>.npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - make publish-gitlab
  only:
    - tags

publish-maven:
  stage: publish
  image: gradle:7.4-jdk8
  needs:
    - push-buf-registry
  dependencies:
    - generate
  script:
    - cd lib/kotlin
    - ./gradlew -Pversion="${CI_COMMIT_TAG}" publish
  only:
    - tags
