name: Base Setup Workflow

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
    secrets:
      pypi_token:
        required: false

jobs:
  command:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Restore Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.venv
          key: ${{ runner.os }}-pyproject-${{ hashFiles('pyproject.toml') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Install required dependencies for ${{ inputs.command }}
        if: ${{ inputs.command == 'lint' }}
        run: |
          python -m pip install --upgrade --disable-pip-version-check pip
          pip install black
          pip install pylint

      - name: Install required dependencies for ${{ inputs.command }}
        if: ${{ inputs.command == 'build' }}
        run: |
          pip install poetry

      - name: Install required dependencies for ${{ inputs.command }}
        if: ${{ inputs.command == 'publish' }}
        run: |
          python -m pip install --upgrade --disable-pip-version-check pip
          python -m pip install --upgrade build twine
          pip install poetry

      - name: Run ${{ inputs.command }}
        env:
          TWINE_PASSWORD: ${{ secrets.pypi_token }}
        run: make ${{ inputs.command }}
