# This workflow will build a buf project
# for more information view https://buf.build/docs/ci-cd/github-actions/
name: Build

on:
  workflow_run:
    workflows:
      - "Lint"
    types:
      - completed
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/buf_build.yaml
