# This workflow will lint a buf project
# for more information view https://buf.build/docs/ci-cd/github-actions/
name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buf Setup
        uses: bufbuild/buf-setup-action@v1

      - name: Run linting
        uses: bufbuild/buf-lint-action@v1

      - name: Check breaking 
        uses: bufbuild/buf-breaking-action@v1
        with:
          # The 'main' branch of the GitHub repository that defines the module.
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main"
