name: Publish PyPI

on:
  push:
    tags:
      # reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags    
      - '*' # Push events to every tag including hierarchical tags like v1.0/beta

permissions:
  contents: read
  pull-requests: read

jobs:  
  publish-pypi:
    runs-on: ubuntu-latest
    name: Publish Python package
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Buf Setup
        uses: bufbuild/buf-setup-action@v1

      - name: Generate
        run: buf generate

      - name: Publish
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          PACKAGE_VERSION: ${{ github.ref_name }}
        run: |
          echo Releasing PyPI Package verion ${{ github.ref_name }}
          cd lib/python
          make publish-pypi
