name: Publish Maven

on:
  push:
    tags:
      # reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags    
      - '*' # Push events to every tag including hierarchical tags like v1.0/beta

permissions:
  contents: read
  pull-requests: read

jobs:
  buf-build:
    uses: ./.github/workflows/buf_build.yaml

  publish-maven:
    runs-on: ubuntu-latest
    name: Publish Kotlin library
    permissions: write-all
    needs: buf-build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download lib artifact
        uses: actions/download-artifact@v3
        with:
          name: lib

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # reference : https://github.com/gradle/gradle-build-action
      - name: Publish Packages
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
          build-root-directory: lib/kotlin
        env:
#          until we have a maven central repository
#          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GH_PACKAGE_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
          GH_RELEASE_ACTOR: ${{ secrets.GH_GITHUB_ACTOR }}
