name: Publish Maven

on:
  push:
    tags:
      # reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags    
      - '*' # Push events to every tag including hierarchical tags like v1.0/beta

permissions:
  contents: read
  pull-requests: read

jobs:
  publish-maven:
    runs-on: ubuntu-latest
    name: Publish Kotlin library
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buf Setup
        uses: bufbuild/buf-setup-action@v1

      - name: Generate
        run: buf generate

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Update gradle.properties
        shell: bash
        run: |
          echo version=${{ github.ref_name }} > gradle.properties
          echo signingKeyId=${{ secrets.SIGNING_KEY_ID }} >> gradle.properties
          echo signingKey=${{ secrets.SIGNING_KEY }} >> gradle.properties
          echo signingPassword=${{ secrets.SIGNING_PASSWORD }} >> gradle.properties

      # reference : https://github.com/gradle/gradle-build-action
      - name: Publish Packages
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            publishLibraryPublicationToGithubRepository
            -Pversion=${{ github.ref_name }}
            -PsigningKeyId=${{ secrets.SIGNING_KEY_ID }}
            -PsigningPassword=${{ secrets.SIGNING_PASSWORD }}
          build-root-directory: lib/kotlin
        env:
          GH_PACKAGE_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
          GH_RELEASE_ACTOR: ${{ secrets.GH_RELEASE_TOKEN }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
