name: Release

on:
    push:
      tags:
        # reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags
        - '*' # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  release:
    uses: SanctumLabs/ci-workflows/.github/workflows/release.yml@main
    with:
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }} 
