name: Slack Notification

on:
  workflow_run:
    workflows:
      - "Lint"
      - "Build"
      - "Publish"
      - "Release"
      - "Gitlab Sync"
      - "BitBucket Sync"
    types:
      - completed

jobs:
  onSuccess:
    uses: SanctumLabs/ci-workflows/.github/workflows/slack_notification.yml
    secrets:
      slack_webhook: ${{ secrets.PIPELINES_SLACK_WEBHOOK }}

  onFailure:
    uses: SanctumLabs/ci-workflows/.github/workflows/slack_notification.yml
    secrets:
      slack_webhook: ${{ secrets.PIPELINES_SLACK_WEBHOOK }}
